apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: nginx-v1
spec:
  host: gke1-vs.takaaki-nginx.xyz
  policies:
  - name: rate-limit-policy
  tls:
    secret: cafe-secret
  upstreams:
  - name: nginx-v1
    service: nginx-v1-svc
    port: 80
  routes:
  - path: /
    action:
      pass: nginx-v1
